if GetLocale() == "ruRU" then
	-- castbar
	DuffedUIConfigUILocalization.castbar = "Castbar"
	DuffedUIConfigUILocalization.castbarenable = "Enable castbar"
	DuffedUIConfigUILocalization.castbarpetenable = "Enable pet castbar"
	DuffedUIConfigUILocalization.castbarcbicons = "Enable castbar-icons"
	DuffedUIConfigUILocalization.castbarcblatency = "Enable castbar latency"
	DuffedUIConfigUILocalization.castbarspark = "Enable castbar spark"
	DuffedUIConfigUILocalization.castbarcolor = "Set color for castbars"
	DuffedUIConfigUILocalization.castbarclasscolor = "Enable classcolor for castbar"
	DuffedUIConfigUILocalization.castbarcbticks = "Enable castbar ticks for channeled casts."

	-- misc
	DuffedUIConfigUILocalization.misc = "Misc"
	DuffedUIConfigUILocalization.misccombatanimation = "Enable Combatanimation"
	DuffedUIConfigUILocalization.miscflightpoint = "Enable Flightpointlist"
	DuffedUIConfigUILocalization.miscilvlcharacter = "Enable itemlevel on character screen"
	DuffedUIConfigUILocalization.miscsComboenergybar = "Enable sCombo-Energybar"
	DuffedUIConfigUILocalization.miscsesenable = "Enable Specswitcherplugin"
	DuffedUIConfigUILocalization.miscsesenablegear = "Enable Equipmentsetbuttons"
	DuffedUIConfigUILocalization.miscsesgearswap = "Enable automatic setswap on respec"
	DuffedUIConfigUILocalization.miscsesset1 = "Set set for first spec (must be an value between 1 - 10)"
	DuffedUIConfigUILocalization.miscsesset2 = "Set set for second spec (must be an value between 1 - 10)"
	DuffedUIConfigUILocalization.miscgold = "Enable shorten golddisplay in chat"
	DuffedUIConfigUILocalization.miscchatalert = "Enable Chatalert"
	DuffedUIConfigUILocalization.miscloc = "Disable Loss of Control for actionbars"
	DuffedUIConfigUILocalization.misclocation = "Enable / Disable location panel on top"
	DuffedUIConfigUILocalization.miscexp_rep = "Show Reputation / XP-Panel on bottom panel"
	DuffedUIConfigUILocalization.miscacm_screen = "Enable automatic Achievment screenshots"

	-- skins
	DuffedUIConfigUILocalization.skins = "Skins"
	DuffedUIConfigUILocalization.skinsenable = "Enable Addonskins"
	DuffedUIConfigUILocalization.skinsbigwigs = "Enable BigWigs-Skin"
	DuffedUIConfigUILocalization.skinsdbm = "Enable DBM-Skin"
	DuffedUIConfigUILocalization.skinsomen = "Enable Omen-Skin"
	DuffedUIConfigUILocalization.skinstinydps = "Enable TinyDPS-Skin"
	DuffedUIConfigUILocalization.skinsblizzardreskin = "Reskin Blizzard frames to match DuffedUI"
	DuffedUIConfigUILocalization.skinscalendarevent = "Disable calendar event textures"

	-- classtimer
	DuffedUIConfigUILocalization.classtimer = "Classtimer"
	DuffedUIConfigUILocalization.classtimerenable = "Enable Classtimer"
	DuffedUIConfigUILocalization.classtimerspark = "Enable spark"
	DuffedUIConfigUILocalization.classtimertargetdebuffs = "Enable targetdebuffs"
	DuffedUIConfigUILocalization.classtimerplayercolor = "Set player color"
	DuffedUIConfigUILocalization.classtimertargetbuffcolor = "Set target buff color"
	DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "Set target debuff color"
	DuffedUIConfigUILocalization.classtimertrinketcolor = "Set trinket color"

	-- duffed
	DuffedUIConfigUILocalization.duffed = "Duffed"
	DuffedUIConfigUILocalization.duffedbossicons = "Enable numbers instead of bossicons on instancemap"
	DuffedUIConfigUILocalization.duffeddrinkannouncement = "Enable Drinkannouncement"
	DuffedUIConfigUILocalization.duffedsayinterrupt = "Enable Interruptannouncement"
	DuffedUIConfigUILocalization.duffedannouncechannel = "Set channel for announcement (|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r or |cffC41F3BINSTANCE|r)"
	DuffedUIConfigUILocalization.duffeddispelannouncement = "Enable Dispelannouncement"

	-- general
	DuffedUIConfigUILocalization.general = "General"
	DuffedUIConfigUILocalization.generalautoscale = "Auto UI Scale"
	DuffedUIConfigUILocalization.generaloverridelowtohigh = "Use High resolution  layout on a Lower resolution"
	DuffedUIConfigUILocalization.generalmultisampleprotect = "Multisampling protection (clean 1px border)"
	DuffedUIConfigUILocalization.generaluiscale = "UI Scale (if auto-scale is disabled)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Set default backdrop color of panels"
	DuffedUIConfigUILocalization.generalbordercolor = "Set default border color of panels"
	DuffedUIConfigUILocalization.generallowres = "Enable Lowreslayout on Highres"
	DuffedUIConfigUILocalization.generaloutlines = "Set outlines for textelements (correct values: THINOUTLINE, OUTLINE, MONOCHROMEOUTLINE)"
	DuffedUIConfigUILocalization.generalclasscolor = "Enable class color for textelements"
	DuffedUIConfigUILocalization.generalclasscoloredborder = "Enable classcolored borders"
	 
	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Nameplates"
	DuffedUIConfigUILocalization.nameplateenable = "Enable Nameplates"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "Enable threat feature, automatically changes by your role"
	DuffedUIConfigUILocalization.nameplateshowhealth = "Show health on nameplate"
	DuffedUIConfigUILocalization.nameplatecombat = "Only show enemy nameplates in-combat"
	DuffedUIConfigUILocalization.nameplategoodcolor = "Good threat color, varies depending if your a tank or dps/heal"
	DuffedUIConfigUILocalization.nameplatebadcolor = "Bad threat color, varies depending if your a tank or dps/heal"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "Losing/Gaining threat color"
	DuffedUIConfigUILocalization.nameplatedebuffs = "Enable debuff display"
	DuffedUIConfigUILocalization.nameplateheight = "Set height of nameplates (default = 7)"
	DuffedUIConfigUILocalization.nameplatewidth = "Set width of nameplates (default = 110)"
	DuffedUIConfigUILocalization.nameplateshowcastbarname = "Show castbar name"
	DuffedUIConfigUILocalization.nameplatenameabbrev = "Show abbreviated names"
	DuffedUIConfigUILocalization.nameplateaurassize = "Set aura size (default = 20)"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "Merchant"
	DuffedUIConfigUILocalization.merchantsellgrays = "Auto sell grey items"
	DuffedUIConfigUILocalization.merchantautorepair = "Auto Repair items"
	DuffedUIConfigUILocalization.merchantsellmisc = "Sell some defined (craps not grey) items automatically"
	DuffedUIConfigUILocalization.merchantautoguildrepair = "Enable Guild Repair Items"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "Bags"
	DuffedUIConfigUILocalization.bagsenable = "Enable all-in-one bag"
	DuffedUIConfigUILocalization.bagsbpr = "Set bagbuttons per row"
	DuffedUIConfigUILocalization.bagsmoveable = "Make bags moveable"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "Data Text"
	DuffedUIConfigUILocalization.datatexttime24 = "Enable 24h time"
	DuffedUIConfigUILocalization.datatextlocaltime = "Use Local Time instead of Server Time"
	DuffedUIConfigUILocalization.datatextbattleground = "Enable Battleground Stats"
	DuffedUIConfigUILocalization.datatexthps_text = "Healing per second, position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextguild = "Guild position (0 for disabled)"
	DuffedUIConfigUILocalization.datatext_arp = "Armor penetration position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextsystem = "Memory position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextbags = "Bags position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextfontsize = "Font size of text"
	DuffedUIConfigUILocalization.datatextfps_ms = "Latency and FPS position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextarmor = "Armor Position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextavd = "Avoidance position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextpower = "Power position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthaste = "Haste position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextfriends = "Friends position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextwowtime = "Time position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextgold = "Gold position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextgold_a = "Enable display of Archaeologyfragment"
	DuffedUIConfigUILocalization.datatextgold_c = "Enable display of Cooking Awards"
	DuffedUIConfigUILocalization.datatextgold_jc = "Enable display of Jewelcrafting Tokens"
	DuffedUIConfigUILocalization.datatextgold_dr = "Enable display of Justice- & Valorpoints"
	DuffedUIConfigUILocalization.datatextgold_pvp = "Enable display of Honor- & Conquestpoints"
	DuffedUIConfigUILocalization.datatextgold_misc = "Enable display of miscellaneous Currency"
	DuffedUIConfigUILocalization.datatextdps_text = "Damage per second position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextcrit = "Crit % position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextdur = "Durability position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Micro Menu position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthit = "Hit position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextmastery = "Mastery position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexttalent = "Display talents (0 for disabled)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Call to Arms & Dungeons (0 for disabled)"
	DuffedUIConfigUILocalization.datatextregen = MANA_REGEN_ABBR
	DuffedUIConfigUILocalization.datatextsmf = "System position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthonorablekills = "Honorable Kills position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextdodge = "Dodge position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextparry = "Parry position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextblock = "Block position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthonor = "Honor  position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextprofession = "Profession position (0 for disabled)"

	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Unit Frames"
	DuffedUIConfigUILocalization.unitframesenable = "Enable DuffedUI Unit Frames"
	DuffedUIConfigUILocalization.unitframeslayout = "Set UF-Layout (1, 2 or 3, default = 2)"
	DuffedUIConfigUILocalization.unitframespercent = "Enable percent display beside player & target"
	DuffedUIConfigUILocalization.unitframeshealthbarcolor = "Set healthbar color"
	DuffedUIConfigUILocalization.unitframesdeficitcolor = "Set deficit color"
	DuffedUIConfigUILocalization.unitframesColorGradient = "Enable ColorGradient for Healthbar"
	DuffedUIConfigUILocalization.unitframesframewidth = "Set frame width"
	DuffedUIConfigUILocalization.unitframestotandpetlines = "Enable lines for pet & ToT (only Layout 1 & 2)"
	DuffedUIConfigUILocalization.unitframesportraitstyle = "Set portraitstyle (MODEL or ICON, only Layout 1 & 2)"
	DuffedUIConfigUILocalization.unitframeslargefocus = "Enable large focus frame (only Layout 1)"
	DuffedUIConfigUILocalization.unitframesbuffrows = "Set buffrows"
	DuffedUIConfigUILocalization.unitframesdebuffrows = "Set debuffrows"
	DuffedUIConfigUILocalization.unitframesvengeancebar = "Enable vengeancebar instead of threatbar"
	DuffedUIConfigUILocalization.unitframespowerClasscolored = "Enable classcolored power bar"
	DuffedUIConfigUILocalization.unitframesfocusdebuffs = "Enable focus debuffs"
	DuffedUIConfigUILocalization.unitframessComboenable = "Enable sCombo-Plugin"
	DuffedUIConfigUILocalization.unitframessComboenergybar = "Enable energy bar for sCombo"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "Color enemy health bar by hostility (for PVP)"
	DuffedUIConfigUILocalization.unitframesauratimer = "Enable timer on auras"
	DuffedUIConfigUILocalization.unitframesauratextscale = "Aura text scale on auras"
	DuffedUIConfigUILocalization.unitframestargetauras = "Enable target auras"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "Low mana indicator (All mana class)"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "Enable Power display on enemy only"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Enable Target of Target debuffs (High Reso)"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "Display total of health/power"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Enable smooth bar"
	DuffedUIConfigUILocalization.unitframescharportrait = "Enable portraits on player and target"
	DuffedUIConfigUILocalization.unitframesunicolor = "Enable Unique color theme (grey health bar)"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Combat Feedback on player and target"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Enable aggro display on yourself"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Enable healcomm"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Display only our debuffs on target"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "Enable Focus target"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar (Dependencies: Class Bar Option need to be enabled)"
	DuffedUIConfigUILocalization.unitframesbordercolor = "Set default border color of panels"
	DuffedUIConfigUILocalization.unitframesruneofpower = "Enable rune of power bar"
	DuffedUIConfigUILocalization.unitframesfader = "Enable Fader for unitframes"
	DuffedUIConfigUILocalization.unitframesminalpha = "Set minimum alpha for Fader (default = 0.1)"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Enable Weakened Soul bar notification (Priest)"
	DuffedUIConfigUILocalization.unitframesclassbar = "Enable class bar"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "Show Druid Mana Bar in Bear/Cat form"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Show Druid Mushroom bar in Balance or Restoration specialization"

	-- raid frames
	DuffedUIConfigUILocalization.raid = "Raid Frames"
	DuffedUIConfigUILocalization.raidshowrange = "Enable party/raid Range alpha display"
	DuffedUIConfigUILocalization.raidraidalphaoor = "Alpha on Party/Raid unit out of range"
	DuffedUIConfigUILocalization.raidshowsymbols = "Show symbols on party/raid"
	DuffedUIConfigUILocalization.raidaggro = "Enable aggro display on party/raid"
	DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "Enable PVE raid Aura Watch (Grid Only)"
	DuffedUIConfigUILocalization.raidgridhealthvertical = "Show health bar vertically for Grid layout"
	DuffedUIConfigUILocalization.raidgridscale = "Grid Scale"
	DuffedUIConfigUILocalization.raidgridvertical = "Display raid groups on Grid vertically"
	DuffedUIConfigUILocalization.raidshowraidpets = "Show Pets in DuffedUI Raid Frames"
	DuffedUIConfigUILocalization.raidshowgroupresurrect = "Show ressurect icon on raid frames"
	DuffedUIConfigUILocalization.raidshowplayerinparty = "Show yourself in party"
	DuffedUIConfigUILocalization.raidgridonly = "Enable Grid only mode for Healer layout"
	DuffedUIConfigUILocalization.raidshowboss = "Enable Boss Unit Frames"
	DuffedUIConfigUILocalization.raidarena = "Enable arena unit frames"
	DuffedUIConfigUILocalization.raidmaintank = "Enable Main Tank"
	DuffedUIConfigUILocalization.raidmainassist = "Enable Main Assist"

	-- loot
	DuffedUIConfigUILocalization.loot = "Loot"
	DuffedUIConfigUILocalization.lootlootframe = "Enable loot window"
	DuffedUIConfigUILocalization.lootautogreed = "Enable auto-greed for green item at max level"
	DuffedUIConfigUILocalization.lootrolllootframe = "Enable item roll window"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "Invite"
	DuffedUIConfigUILocalization.inviteautoaccept = "Enable Auto-Invite (Friends and Guildmates)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipenable = "Enable tooltip"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Hide tooltip in combat"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Hide tooltip on action bar buttons"
	DuffedUIConfigUILocalization.tooltiphideuf = "Hide tooltip on unit frames"
	DuffedUIConfigUILocalization.tooltipcursor = "Enable cursor tooltip"
	DuffedUIConfigUILocalization.tooltipids = "Show spell / item-id on tooltip"
	DuffedUIConfigUILocalization.tooltipilvl = "Enable Itemleveldisplay on tooltip"
	 
	-- error
	DuffedUIConfigUILocalization.error = "Error Message"
	DuffedUIConfigUILocalization.errorenable = "Hide spamming error in the middle of your screen"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Action Bars"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "Hide Shapeshift bar or Totem bar"
	DuffedUIConfigUILocalization.actionbarshowgrid = "Always show Grid on action bar"
	DuffedUIConfigUILocalization.actionbarenable = "Enable DuffedUI action bar"
	DuffedUIConfigUILocalization.actionbarrb = "Enable right bar on mouseover"
	DuffedUIConfigUILocalization.actionbarhotkey = "Show hotkey on buttons"
	DuffedUIConfigUILocalization.actionbarssmo = "Shapeshift bar or Totem bar on mouseover"
	DuffedUIConfigUILocalization.actionbarrbn = "Number of action bars on the bottom (1 or 2)"
	DuffedUIConfigUILocalization.actionbarrn = "Number of action bars on right (0, 1, 2 or 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Size of the main action buttons"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Spacing of the main action buttons"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Size of pet/shapeshift buttons"
	DuffedUIConfigUILocalization.actionbarownshdbar = "Use an empty bar for shadow dance (rogue) instead of stealth bar"
	DuffedUIConfigUILocalization.actionbarownmetabar = "Use an empty bar for Metamorphosis (warlock) instead of main bar"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "Use an empty bar for each stance (warrior) instead of main bar"
	DuffedUIConfigUILocalization.actionbarmacro = "Show macro text on action bar"
	DuffedUIConfigUILocalization.actionbarbutton2 = "Hide the button between datatextpanel (works only without actionbarswap)"
	DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "Set rightbars on mouseover"
	DuffedUIConfigUILocalization.actionbarswap = "Swap Bar3 with Bar1"
	DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "Set petbar to always visible"
	DuffedUIConfigUILocalization.actionbarshapeshiftborder = "Enable Shapeshiftbarborder"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "Enable mouseover for Shapeshiftbar"
	DuffedUIConfigUILocalization.actionbarverticalshapeshift = "Enable vertical Shapeshiftbar"
	DuffedUIConfigUILocalization.actionbarborderhighlight = "Enable prochighlight from DuffedUI (default = disabled)"
	DuffedUIConfigUILocalization.actionbarlayout = "Set actionbarlayout (1 or 2, default = 1)"
	DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "Set petbar horizontal"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Cooldowns"
	DuffedUIConfigUILocalization.cooldownenable = "Enable cooldown number on buttons"
	DuffedUIConfigUILocalization.cooldowntreshold = "Turn cooldown number red at X value"

	-- raidcooldowns
	DuffedUIConfigUILocalization.rcd = "RaidCooldowns"
	DuffedUIConfigUILocalization.rcdenable = "Enable RaidCooldowns"
	DuffedUIConfigUILocalization.rcdraid = "Enable cooldown announcement for raid"
	DuffedUIConfigUILocalization.rcdparty = "Enable cooldown announcement for party"
	DuffedUIConfigUILocalization.rcdarena = "Enable cooldown announcement for arena"

	-- spellcooldowns
	DuffedUIConfigUILocalization.scd = "SpellCooldowns"
	DuffedUIConfigUILocalization.scdenable = "Enable the SpellCooldown-Plugin"
	DuffedUIConfigUILocalization.scdsize = "Set size for icons (default = 36)"
	DuffedUIConfigUILocalization.scdspacing = "Set spacing of icons (default = 10)"
	DuffedUIConfigUILocalization.scdfade = "Set fading (values: 0 one color, 1 green to red, 2 red to green)"
	DuffedUIConfigUILocalization.scddisplay = "Set display of cooldown (values: SPIRAL or STATUSBAR, default = STATUSBAR)"
	DuffedUIConfigUILocalization.scddirection = "Set direction of cooldowndisplay (values: HORIZONTAL or VERTICAL, default = HORIZONTAL)"
	DuffedUIConfigUILocalization.scdfsize = "Set fontsize"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "Chat"
	DuffedUIConfigUILocalization.chatenable = "Enable DuffedUI Chat"
	DuffedUIConfigUILocalization.chatwhispersound = "Play sound when receiving private message"
	DuffedUIConfigUILocalization.chatbackground = "Enable chat panel background"
	DuffedUIConfigUILocalization.chatfading = "Enable chatfading"
	DuffedUIConfigUILocalization.chattextright = "Set textalign to right for right chatframe"

	-- buff
	DuffedUIConfigUILocalization.auras = "Auras"
	DuffedUIConfigUILocalization.aurasplayer = "Enable DuffedUI Buff/Debuff Frames"
	DuffedUIConfigUILocalization.aurasconsolidate = "Enable Consolidate Buffs"
	DuffedUIConfigUILocalization.aurasflash = "Enable flashing animation on aura less than 30 seconds"
	DuffedUIConfigUILocalization.aurasclassictimer = "Display classic timer on player auras"
	DuffedUIConfigUILocalization.aurasbuffnotice = "Enable BuffNotice"
	DuffedUIConfigUILocalization.auraswarning = "Enable warningsound for BuffNotice"
	DuffedUIConfigUILocalization.aurasbufftracker = "Enable Bufftrackerplugin"
	DuffedUIConfigUILocalization.auraswrap = "Set wrap for buffs (default = 18)"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Reset"
	DuffedUIConfigUILocalization.option_button_load = "Apply Settings"
	DuffedUIConfigUILocalization.option_button_close = "Close"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Set settings Per-Character"
	DuffedUIConfigUILocalization.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
	DuffedUIConfigUILocalization.option_resetall = "Are you sure you want to reset all of your settings to Default?"
	DuffedUIConfigUILocalization.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
	DuffedUIConfigUILocalization.option_makeselection = "You must make a selection before you can continue to config."
end